"""Public Stage 0 model-gateway boundary."""

from .gateway import (
    CallBudget,
    GatewayBudgetExceeded,
    GatewayCallResult,
    GatewayConfig,
    GatewayContextError,
    GatewayError,
    GatewayMode,
    GatewayProviderError,
    GatewayRouteBlocked,
    GatewaySafetyBlock,
    GatewaySchemaViolation,
    GatewayTimeout,
    GatewayValidationError,
    ModelAdapter,
    ModelGateway,
    ModelRouteResolver,
    PermanentProviderError,
    RateLimitProviderError,
    SafetyBlockProviderError,
    TransientProviderError,
    ValidationPhase,
)
from .mock_factory import (
    AdapterResult,
    DeterministicMockAdapter,
    DeterministicMockFactory,
    MockBehavior,
    build_mock_request,
    build_trusted_context,
)
from .registry import (
    PROMPT_CONTRACTS,
    PROMPT_SPECS,
    PromptSpec,
    assert_registry_complete,
    prompt_spec,
)

__all__ = [
    "AdapterResult",
    "CallBudget",
    "DeterministicMockAdapter",
    "DeterministicMockFactory",
    "GatewayBudgetExceeded",
    "GatewayCallResult",
    "GatewayConfig",
    "GatewayContextError",
    "GatewayError",
    "GatewayMode",
    "GatewayProviderError",
    "GatewayRouteBlocked",
    "GatewaySafetyBlock",
    "GatewaySchemaViolation",
    "GatewayTimeout",
    "GatewayValidationError",
    "MockBehavior",
    "ModelAdapter",
    "ModelGateway",
    "ModelRouteResolver",
    "PROMPT_CONTRACTS",
    "PROMPT_SPECS",
    "PermanentProviderError",
    "PromptSpec",
    "RateLimitProviderError",
    "SafetyBlockProviderError",
    "TransientProviderError",
    "ValidationPhase",
    "assert_registry_complete",
    "build_mock_request",
    "build_trusted_context",
    "prompt_spec",
]

